### ISSUE TITLE
Incorrect structure for err argument in finally cb

### ISSUE THREAD

**Issue by triadium** [mynameisdaniil/yaff#4]
*main.js*
lines #155-156, *this.lastError* is already array.

And my code:
```javascript
tasks.finally(function(err, result){
  if(err){
      console.log(util.inspect(err, {depth: null}));
  }
} 
```
with **[e]** (v0.1.2) outputs:
[ [ **<-- incorrect structure**
 [ { [Error: ENOENT, open 'D:\projects\template.tmpl']
errno: 34,
code: 'ENOENT',
path: 'D:\projects\template.tmpl' } ],
null **<-- undefined item?**
] ]**<-- incorrect structure**

Before v0.1.2 (master branch) - 
with only **e** (wo []) outputs:
[ { [Error: ENOENT, open 'D:\projects\template.tmpl']
errno: 34,
code: 'ENOENT',
path: 'D:\projects\template.tmpl' } ]
**And it's correct structure.**

**Comment by mynameisdaniil** [comment]
Fixed. See 0.1.3. Thanks for feedback.

**Comment by triadium** [comment]
Ok. Thanks!
